import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider"
import { DotBackground } from "@/components/dot-background"
import "./globals.css"

const font = JetBrains_Mono({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Oniguiri list",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <DotBackground>
            {children}
          </DotBackground>
        </ThemeProvider>
      </body>
    </html>
  )
}
