import { Metadata as Meta } from "next/types"

export const Metadata: Meta = {
    title: "Oniguiri list",
    description: "Generated by create next app",
    generator: "Next.js",
    manifest: "/manifest.json",
    keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
    themeColor: "black",
    colorScheme: "dark light",
    authors: [
        { name: "Nathan Ferreira" },
        {
            name: "Nathan Ferreira",
            url: "https://www.linkedin.com/in/raazeshp96/",
        },
    ],
    viewport:
        "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
    icons: [
        { rel: "apple-touch-icon", url: "/icon-128x128.png" },
        { rel: "icon", url: "/icon-128x128.png" },
    ],
}